name: Deploy Nuxt 3 App to Alibaba Cloud

on:
  push:
    branches:
      - master  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install pnpm
        run: npm install -g pnpm@9.12

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.14'  # 指定 Node.js 版本

      - name: Install dependencies
        run: pnpm install

      - name: Build Nuxt 3 project
        run: pnpm run build

      - name: Deploy to Alibaba Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          source: ".output"  # Nuxt 3 构建后的输出目录
          target: ${{ secrets.APP_PATH }}  # 服务器上的目标目录

      - name: Restart Node.js service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SSH_KEY }}
          script: |
            cd ${{ secrets.APP_PATH }}
            if pm2 list | grep -q "r2-master-fe"; then
              echo "Application is already running. Restarting..."
              pm2 restart r2-master-fe
            else
              echo "Application is not running. Starting..."
              pm2 start .output/server/index.mjs --name "r2-master-fe"
            fi